export enum BotState {
  SPAWNING = 'SPAWNING',
  IDLE = 'IDLE',
  WANDERING = 'WANDERING',
  FOLLOWING = 'FOLLOWING',
  MINING = 'MINING',
  PATROLLING = 'PATROLLING',
  HOSTILE = 'HOSTILE',
  INSTINCT = 'INSTINCT',
  EXECUTING_TASK = 'EXECUTING_TASK',
  BUILDING = 'BUILDING',
  DISCONNECTED = 'DISCONNECTED',
}

export enum BotMode {
  PRIMITIVE = 'primitive',
  CODEGEN = 'codegen',
}
